# Generated by Django 5.0.3 on 2024-04-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_alter_result_error_alter_result_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['-id']},
        ),
    ]
